/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Users.User;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JMenuBar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author IBM
 */
public class UserHome extends javax.swing.JFrame {
    User player = null;
    WelcomeScreen previous = null;
    /**
     * Creates new form UserHome
     */
    public UserHome() {
        initComponents();
    }
    
      public UserHome(WelcomeScreen previous) {
        this();
        this.previous = previous;
    }
    
    public UserHome(User player,WelcomeScreen previous) {
        this(previous);
        this.player = player;
        labWelcomeUser.setText(labWelcomeUser.getText() + player.getFirstName()
                + " " + player.getLastName());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPlay = new javax.swing.JButton();
        btnScoreTable = new javax.swing.JButton();
        labWelcomeUser = new javax.swing.JLabel();
        labBack = new javax.swing.JLabel();
        labBackground = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnuAccount = new javax.swing.JMenu();
        mnuItmAbout = new javax.swing.JMenuItem();
        mnuItmChangePassword = new javax.swing.JMenuItem();
        mnuItmRemoveAccount = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        btnPlay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPlay.setText("Play Blackjack");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlay);
        btnPlay.setBounds(20, 100, 200, 25);

        btnScoreTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnScoreTable.setText("Show Score Table");
        btnScoreTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScoreTableActionPerformed(evt);
            }
        });
        getContentPane().add(btnScoreTable);
        btnScoreTable.setBounds(20, 150, 200, 30);

        labWelcomeUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labWelcomeUser.setForeground(new java.awt.Color(255, 255, 255));
        labWelcomeUser.setText("Welcome ");
        labWelcomeUser.setToolTipText("");
        getContentPane().add(labWelcomeUser);
        labWelcomeUser.setBounds(20, 30, 290, 30);

        labBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        labBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labBackMouseClicked(evt);
            }
        });
        getContentPane().add(labBack);
        labBack.setBounds(10, 280, 64, 70);

        labBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cardBackground.jpg"))); // NOI18N
        getContentPane().add(labBackground);
        labBackground.setBounds(0, 0, 672, 380);

        mnuAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/account.png"))); // NOI18N
        mnuAccount.setText("My Account");

        mnuItmAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/about.png"))); // NOI18N
        mnuItmAbout.setText("About");
        mnuItmAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmAboutActionPerformed(evt);
            }
        });
        mnuAccount.add(mnuItmAbout);

        mnuItmChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/password.png"))); // NOI18N
        mnuItmChangePassword.setText("Change Password");
        mnuItmChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmChangePasswordActionPerformed(evt);
            }
        });
        mnuAccount.add(mnuItmChangePassword);

        mnuItmRemoveAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/removeAccount.png"))); // NOI18N
        mnuItmRemoveAccount.setText("Remove My Account");
        mnuItmRemoveAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmRemoveAccountActionPerformed(evt);
            }
        });
        mnuAccount.add(mnuItmRemoveAccount);

        menuBar.add(mnuAccount);

        setJMenuBar(menuBar);

        setSize(new java.awt.Dimension(689, 420));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

public JMenuBar getMenu()
{
    return menuBar;
}
    
//protected void removeListeners(){
//    this.mnuItmAbout.removeActionListener(this);
//    this.mnuItmChangePassword.removeActionListener(this);
//    this.mnuItmRemoveAccount.removeActionListener(this);
//}

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        this.setVisible(false);  
        GameORG game = new GameORG(player,this);
        game.initializeGUI();
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnScoreTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScoreTableActionPerformed
        this.setVisible(false);  
        ScoreTable scoreTable = new ScoreTable(this,player);
        scoreTable.setVisible(true);
    }//GEN-LAST:event_btnScoreTableActionPerformed

    private void mnuItmChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmChangePasswordActionPerformed
        JTextField oldPassword = new JTextField();
        JTextField newPassword = new JPasswordField();
        Object[] message = {
            "Old Password:", oldPassword,
            "New Password:", newPassword
        };

        int option = JOptionPane.showConfirmDialog(null, message, "Change Password", 
                JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE);
        if (option == JOptionPane.OK_OPTION) {
            if (oldPassword.getText() == null || newPassword.getText() == null)
            {
                        
            }
            else if (player.changePassword(oldPassword.getText(), newPassword.getText())) {
                JOptionPane.showMessageDialog(null, "Password Changed Successfully");
               this.dispatchEvent(new WindowEvent(this,WindowEvent.WINDOW_CLOSING));
            } else {
                JOptionPane.showMessageDialog(null, "Incorecct Password!");
            }
        }   
    }//GEN-LAST:event_mnuItmChangePasswordActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int confirmed = JOptionPane.showConfirmDialog(null, 
        "Are you sure you want to exit the program?", "Exit Program",
        JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);

    if (confirmed == JOptionPane.YES_OPTION) {
      System.exit(0);
    }
        
    }//GEN-LAST:event_formWindowClosing

    private void mnuItmAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmAboutActionPerformed

        int per = player.getPermission();
        String type = (per == 1 ? "Admin" : "User");
        String about = "Account Type: " + type + "\nAbout " + player.getUserName() + "\n\nName: "
                + player.getFirstName() + " " + player.getLastName() + "\nGender: " + player.getGender() + "\n";
        JOptionPane.showMessageDialog(null, about);
    }//GEN-LAST:event_mnuItmAboutActionPerformed

    private void mnuItmRemoveAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmRemoveAccountActionPerformed
        int confirmed = JOptionPane.showConfirmDialog(null, 
        "Are you sure you want to remove your account?", "Account",
        JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);

    if (confirmed == JOptionPane.YES_OPTION) {
       JOptionPane.showMessageDialog(null,"Hope to see you soon!");
      player.removeAccount(player);
      this.dispose();
      previous.setVisible(true);
    }
    }//GEN-LAST:event_mnuItmRemoveAccountActionPerformed

    private void labBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labBackMouseClicked
        this.dispose();
        previous.setVisible(true);
    }//GEN-LAST:event_labBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btnPlay;
    protected javax.swing.JButton btnScoreTable;
    protected javax.swing.JLabel labBack;
    protected javax.swing.JLabel labBackground;
    protected javax.swing.JLabel labWelcomeUser;
    protected javax.swing.JMenuBar menuBar;
    protected javax.swing.JMenu mnuAccount;
    protected javax.swing.JMenuItem mnuItmAbout;
    protected javax.swing.JMenuItem mnuItmChangePassword;
    protected javax.swing.JMenuItem mnuItmRemoveAccount;
    // End of variables declaration//GEN-END:variables
}
