package Forms;


import Users.User;
import blackjack.DB;
import blackjack.DB;
import Forms.GameORG;
import java.awt.Component;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.text.JTextComponent;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nadav
 */
public class WelcomeScreen extends javax.swing.JFrame {

      DB db = DB.getInstance();
    /**
     * Creates new form NewJFrame
     */
    public WelcomeScreen() {
        initComponents();
          try {
              db.initUsers();
          } catch (Exception ex) {
              ex.printStackTrace();
          }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labUserName = new javax.swing.JLabel();
        labPassword = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnSignUp = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        labBlackjack = new javax.swing.JLabel();
        btnGuest = new javax.swing.JButton();
        labBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        labUserName.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        labUserName.setText("User Name : ");
        labUserName.setName("labUserName"); // NOI18N
        getContentPane().add(labUserName);
        labUserName.setBounds(10, 80, 90, 20);

        labPassword.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        labPassword.setText("Password : ");
        labPassword.setName("labPassword"); // NOI18N
        getContentPane().add(labPassword);
        labPassword.setBounds(10, 120, 90, 20);

        txtUserName.setText("Enter your user name here");
        txtUserName.setName("txtUserName"); // NOI18N
        txtUserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserNameMouseClicked(evt);
            }
        });
        getContentPane().add(txtUserName);
        txtUserName.setBounds(100, 80, 160, 25);
        txtUserName.getAccessibleContext().setAccessibleName("txtUserName");

        txtPassword.setText("Enter your password here");
        txtPassword.setName("txtPassword"); // NOI18N
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });
        getContentPane().add(txtPassword);
        txtPassword.setBounds(100, 120, 160, 25);
        txtPassword.getAccessibleContext().setAccessibleName("txtPassword");
        txtPassword.getAccessibleContext().setAccessibleDescription("");

        btnSignUp.setText("Sign Up");
        btnSignUp.setName("btnSignUp"); // NOI18N
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignUp);
        btnSignUp.setBounds(180, 160, 80, 30);
        btnSignUp.getAccessibleContext().setAccessibleName("btnSignUp");

        btnLogin.setText("Login");
        btnLogin.setName("btnLogin"); // NOI18N
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(100, 160, 70, 30);

        labBlackjack.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        labBlackjack.setText("BlackJack");
        getContentPane().add(labBlackjack);
        labBlackjack.setBounds(70, 10, 280, 50);

        btnGuest.setText("Play as a Guest");
        btnGuest.setMaximumSize(new java.awt.Dimension(57, 23));
        btnGuest.setMinimumSize(new java.awt.Dimension(57, 23));
        btnGuest.setPreferredSize(new java.awt.Dimension(60, 30));
        btnGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuestActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuest);
        btnGuest.setBounds(0, 220, 140, 30);

        labBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PokerChips.jpg"))); // NOI18N
        labBackground.setName("labBackground"); // NOI18N
        getContentPane().add(labBackground);
        labBackground.setBounds(0, 0, 620, 390);
        labBackground.getAccessibleContext().setAccessibleName("labBackground");

        setSize(new java.awt.Dimension(636, 425));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserNameMouseClicked
        txtUserName.setText("");
    }//GEN-LAST:event_txtUserNameMouseClicked

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        txtPassword.setText("");
    }//GEN-LAST:event_txtPasswordMouseClicked

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        String userName = txtUserName.getText().toString();
        String password = txtPassword.getText().toString();
        User player = db.login(userName, password);
        if (player!= null)
        {
        clearComponents();
        this.setVisible(false);
        if (player.getPermission() == 2)
        {
            UserHome userHome = new UserHome(player,this);
            userHome.setVisible(true);
        }
        else if (player.getPermission() == 1) {//admin
            AdminHome adminHome = new AdminHome(player,this);
            adminHome.setVisible(true);
        }
        else{
           JOptionPane.showMessageDialog(null, "User doesn't exist", "Error", JOptionPane.INFORMATION_MESSAGE);   
         clearComponents();
        }
        }
    }//GEN-LAST:event_btnLoginMouseClicked

    private void clearComponents() {
        Component[] components = this.getContentPane().getComponents();
        for (Component component : components) {
            if (component instanceof JTextField || component instanceof JTextArea) {
                JTextComponent specificObject = (JTextComponent) component;
                specificObject.setText("");
            }
        }
    }
    
    private void btnGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuestActionPerformed
        GameORG game;
          game = new GameORG();
            game.initializeGUI();
           this.initComponents();
        this.setVisible(false);
    }//GEN-LAST:event_btnGuestActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        SignUpScreen signUpScreen = new SignUpScreen(this);
        this.setVisible(false);
        signUpScreen.setVisible(true);
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int confirmed = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to exit the program?", "Exit Program",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (confirmed == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WelcomeScreen welcomeScreen = new WelcomeScreen();
                welcomeScreen.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuest;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel labBackground;
    private javax.swing.JLabel labBlackjack;
    private javax.swing.JLabel labPassword;
    private javax.swing.JLabel labUserName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
